#!/bin/bash

echo "************ Cronny Started ***************"
#date >> ${OPENSHIFT_DATA_DIR}essay_train-start.log

python ${OPENSHIFT_REPO_DIR}wsgi/myproject/corn.py

echo "************ Cronny Executed ***************"
#date >> ${OPENSHIFT_DATA_DIR}essay_train-end.log
